import fs from 'node:fs/promises';import path from 'node:path';import {fileURLToPath} from 'node:url';import {chromium} from 'playwright';import assert from 'node:assert/strict';
const root=fileURLToPath(new URL('./',import.meta.url)),dist=path.join(root,'docs'),out=path.join(root,'outputs/review');
const checkFiles=['index.html','salon/index.html','expo/index.html','mason/index.html','downloads/交付说明.html','downloads/会展产品规格与验收.html','downloads/WordPress安装说明.html','downloads/竞品对比与升级说明.html'];let localLinks=0;
for(const file of checkFiles){const html=await fs.readFile(path.join(dist,file),'utf8');for(const match of html.matchAll(/(?:href|src)="([^"#]+)(?:#[^"]*)?"/g)){const ref=match[1];if(/^(https?:|data:)/.test(ref))continue;const target=path.resolve(path.dirname(path.join(dist,file)),ref);await fs.access(target);localLinks++}}
await fs.mkdir(out,{recursive:true});const browser=await chromium.launch({channel:'chrome',headless:true});const p=await browser.newPage({viewport:{width:1440,height:1000}});const errors=[];p.on('pageerror',e=>errors.push(e.message));
await p.goto('http://127.0.0.1:8765/mason/index.html');await p.screenshot({path:path.join(out,'mason-desktop.png'),fullPage:true});await p.locator('#collection').screenshot({path:path.join(out,'mason-collection-detail.png')});await p.setViewportSize({width:390,height:844});await p.screenshot({path:path.join(out,'mason-mobile.png'),fullPage:true});
await p.setViewportSize({width:1440,height:1000});await p.goto('http://127.0.0.1:8765/');await p.screenshot({path:path.join(out,'review-desktop.png'),fullPage:true});for(const link of ['downloads/门店经营模板.xlsx','downloads/mason-metal-child.zip','downloads/MASON-METAL-Elementor首页.json','downloads/电鸭三套成品样品.zip']){const r=await p.request.get('http://127.0.0.1:8765/'+encodeURI(link));assert.equal(r.status(),200)}
// Exercise the isolated JavaScript delivered in the WordPress child theme, without claiming a PHP/WordPress runtime test.
let body=await fs.readFile(path.join(root,'wordpress/mason-metal-child/partials/home.html'),'utf8');body=body.replaceAll('src="assets/silver-editorial.png"','src="http://127.0.0.1:8765/mason/assets/silver-editorial.png"');await p.setContent(body);await p.addScriptTag({content:"window.MASON_ASSET_URL='http://127.0.0.1:8765/mason/assets/silver-editorial.png'"});await p.addScriptTag({path:path.join(root,'wordpress/mason-metal-child/assets/shared.js')});await p.addScriptTag({path:path.join(root,'wordpress/mason-metal-child/assets/app.js')});assert.equal(await p.locator('#products .product').count(),4);await p.waitForFunction(()=>[...document.querySelectorAll('#products img')].every(x=>x.complete&&x.naturalWidth>0));assert.ok(await p.locator('#products img').first().getAttribute('src').then(s=>s.includes('/mason/assets/fold-ring.png')));await p.locator('[data-compare=MM01]').click();await p.locator('[data-compare=MM02]').click();await p.locator('#opencompare').click();assert.equal(await p.locator('.comparison thead th').count(),3);await p.locator('[data-close=comparedialog]').click();await p.locator('#products .product').first().click();await p.getByRole('button',{name:'Add to bag',exact:true}).click();assert.ok((await p.locator('#bagcount').textContent())!=='(0)');assert.deepEqual(errors,[]);
// File protocol is the restart-independent handoff.
await p.goto(new URL('docs/index.html',import.meta.url).href);await p.getByRole('link',{name:'打开会展原型',exact:true}).click();await p.getByRole('button',{name:'新建活动'}).click();assert.ok(await p.locator('#eventdialog').isVisible());
await p.goto(new URL('docs/mason/index.html',import.meta.url).href);await p.locator('[data-compare=MM01]').click();await p.locator('[data-compare=MM02]').click();await p.locator('#opencompare').click();assert.ok(await p.locator('#comparedialog').isVisible());await p.goto('http://127.0.0.1:8765/downloads/'+encodeURI('竞品对比与升级说明.html'));await p.setViewportSize({width:390,height:844});assert.ok(await p.evaluate(()=>document.documentElement.scrollWidth<=innerWidth));await p.screenshot({path:path.join(out,'comparison-report-mobile.png'),fullPage:true});assert.deepEqual(errors,[]);await browser.close();const result={local_links:localLinks,http_downloads:'pass',wordpress_javascript:'pass',wordpress_image_paths:'pass',offline_file_preview:'pass',comparison_report_mobile:'pass',errors};await fs.writeFile(path.join(out,'final-checks.json'),JSON.stringify(result,null,2));console.log(JSON.stringify(result));
