import {chromium} from 'playwright';
import fs from 'node:fs/promises';
import {fileURLToPath} from 'node:url';
import assert from 'node:assert/strict';
const root=new URL('./',import.meta.url),out=new URL('outputs/review/',root);
await fs.mkdir(out,{recursive:true});await fs.mkdir(new URL('outputs/v2/',root),{recursive:true});const browser=await chromium.launch({channel:'chrome',headless:true});
const context=await browser.newContext({viewport:{width:1440,height:1000},acceptDownloads:true});
const page=await context.newPage();page.setDefaultTimeout(10000);
const errors=[],checks=[];page.on('pageerror',e=>errors.push(e.message));
const base='http://127.0.0.1:8770/';
const go=async name=>page.locator(`[data-view=${name}]`).click();
const snap=async name=>{await page.locator('.toast').evaluateAll(xs=>xs.forEach(x=>x.remove()));await page.screenshot({path:fileURLToPath(new URL(name+'.png',out)),fullPage:true})};
try{
 await page.goto(base+'expo/index.html');await page.locator('#reset').click();
 await go('tickets');await page.locator('[data-ticket=guest]').click();await page.locator('#ticketform [name=capacity]').fill('2');await page.locator('#ticketform .primary').click();await page.getByText('票种名额不能少于已报名人数',{exact:true}).waitFor();assert.equal(await page.evaluate(()=>Expo.getState().events[0].tickets[1].capacity),50);await page.locator('#ticketform [name=capacity]').fill('3');await page.locator('#ticketform .primary').click();
 await page.locator('#preview').click();await page.locator('#publicform [name=name]').fill('票种容量测试');await page.locator('#publicform [name=company]').fill('示例大学');await page.locator('#publicform [name=phone]').fill('13998765432');assert.ok(await page.locator('#publicform [value=guest]').evaluate(e=>e.disabled));await page.locator('#publicform .primary').click();assert.equal(await page.evaluate(()=>Expo.getState().guests.length),13);const dl=page.waitForEvent('download');await page.locator('#downloadpass').click();assert.match((await dl).suggestedFilename(),/^参会凭证-G/);await page.locator('#passdialog [data-close]').click();
 const duplicate=await page.evaluate(()=>{try{Expo.register({name:'重复',company:'学校',phone:'13998765432',ticket:'standard'});return ''}catch(e){return e.message}});assert.match(duplicate,/已经报名/);const full=await page.evaluate(()=>{try{Expo.register({name:'特邀',company:'学校',phone:'13998765433',ticket:'guest'});return ''}catch(e){return e.message}});assert.match(full,/票种名额已满/);checks.push('会展：票种容量、人数下限、重复报名、参会者报名与凭证下载');
 await go('agenda');await page.locator('#addsession').click();for(const [k,v]of Object.entries({name:'冲突测试',date:'2026-10-24',start:'10:00',end:'10:45',room:'主会场',speaker:'演示嘉宾'}))await page.locator(`#sessionform [name=${k}]`).fill(v);await page.locator('#sessionform .primary').click();await page.getByText('该会场在这个时段已有议程，请调整时间',{exact:true}).waitFor();assert.equal(await page.evaluate(()=>Expo.getState().events[0].agenda.length),3);await page.locator('#sessionform [name=start]').fill('14:00');await page.locator('#sessionform [name=end]').fill('15:00');await page.locator('#sessionform [name=name]').fill('新议程演示');await page.locator('#sessionform .primary').click();assert.equal(await page.evaluate(()=>Expo.getState().events[0].agenda.length),4);await snap('expo-agenda');checks.push('会展：议程冲突阻止保存；可用时间段成功保存');
 await go('attendees');assert.equal(await page.locator('tbody tr').count(),10);await page.locator('#nextpage').click();assert.equal(await page.locator('tbody tr').count(),3);await page.locator('#prevpage').click();await page.locator('[data-select=G005]').check();await page.locator('[data-select=G006]').check();await page.locator('#batchcheck').click();assert.equal(await page.evaluate(()=>Expo.getState().guests.filter(g=>g.checked).length),6);
 await page.locator('[data-undo=G005]').click();await page.locator('#confirmform [name=reason]').fill('测试误签撤销');await page.locator('#confirmform .primary').click();assert.equal(await page.evaluate(()=>Expo.getState().guests.find(g=>g.id==='G005').checked),false);
 await page.locator('[data-cancel=G006]').click();await page.locator('#confirmform [name=reason]').fill('参会计划变更');await page.locator('#confirmform .primary').click();assert.equal(await page.evaluate(()=>Expo.getState().guests.find(g=>g.id==='G006').status),'cancelled');assert.equal(await page.evaluate(()=>Expo.getState().guests.filter(g=>g.status!=='cancelled').length),12);await page.locator('#statusfilter').selectOption('cancelled');assert.equal(await page.locator('tbody tr').count(),1);assert.ok(await page.locator('[data-select=G006]').isDisabled());
 await page.locator('#activeevent').selectOption('EV002');assert.equal(await page.locator('#statusfilter').inputValue(),'');assert.equal(await page.locator('#ticketfilter').inputValue(),'');await page.locator('#activeevent').selectOption('EV001');await go('checkin');await page.locator('#checksearch').fill('G006');await page.locator('#searchform .primary').click();assert.ok(await page.locator('[data-check=G006]').isDisabled());checks.push('会展：分页、批量签到、撤销与原因、取消释放名额、取消禁止签到、切换活动清空筛选');
 await go('booths');await page.locator('[data-booth=A02]').click();await page.locator('#releasebooth').click();assert.equal(await page.evaluate(()=>Expo.getState().events[0].booths.A02),undefined);
 await go('reports');assert.ok(await page.locator('#content').textContent().then(s=>s.includes('测试误签撤销')&&s.includes('参会计划变更')));await snap('expo-reports');
 await go('messages');await page.locator('#messageaudience').selectOption('pending');await page.locator('#messagenote').fill('请提前 20 分钟到场');await page.locator('#messageform .primary').click();const messageDownload=page.waitForEvent('download');await page.locator('#downloadmessage').click();assert.equal((await messageDownload).suggestedFilename(),'活动沟通草稿.txt');await page.reload();assert.ok(await page.evaluate(()=>Expo.getState().logs.some(l=>l.text.includes('参会计划变更'))));checks.push('会展：展位释放、统计与操作记录、沟通草稿下载、刷新保留数据');
 await page.locator('#reset').click();await snap('expo-desktop');await page.locator('#preview').click();await snap('expo-attendee-preview');await page.locator('#publicdialog [data-close]').click();
 await page.goto(base+'salon/index.html');assert.ok(await page.locator('.business-brief').textContent().then(s=>s.includes('暂无上期数据')));await page.locator('#lastweek').click();assert.equal(await page.locator('#from').inputValue(),'2026-09-24');const growth=await page.evaluate(()=>{const d=Salon.getData(),a=d.filter(x=>x.date>='2026-09-24'),b=d.filter(x=>x.date>='2026-09-17'&&x.date<='2026-09-23');const sum=a=>a.reduce((t,x)=>t+x.paid-x.refund,0);return ((sum(a)-sum(b))/sum(b)*100).toFixed(1)+'%'});assert.ok(await page.locator('.business-brief').textContent().then(s=>s.includes(growth)));await page.locator('#wholemonth').click();
 await go('orders');await page.locator('#ordersearch').fill('自然款美睫');assert.equal(await page.locator('tbody tr:visible').count(),38);await go('reconcile');await page.locator('#onlyissues').check();const original=await page.evaluate(()=>Salon.getData().map(r=>[r.id,r.bank]));await page.locator('[data-note]').first().click();await page.locator('#noteform [name=owner]').fill('演示店长');await page.locator('#noteform [name=note]').fill('等待支付渠道结算单，次日核对。');await page.locator('#noteform .primary').click();assert.deepEqual(await page.evaluate(()=>Salon.getData().map(r=>[r.id,r.bank])),original);assert.equal(await page.locator('tbody tr').count(),8);const csvDL=page.waitForEvent('download');await page.locator('#exportissues').click();assert.equal((await csvDL).suggestedFilename(),'到账核查清单.csv');await snap('salon-reconciliation');await page.reload();await go('reconcile');assert.ok(await page.locator('.noted').count()>0);await go('overview');await snap('salon-desktop');checks.push('门店：上期口径准确、快捷日期、流水搜索、备注保存不改变财务状态、核查清单导出');
 await page.goto(base+'mason/index.html');await page.evaluate(()=>{localStorage.removeItem('mason-saved');localStorage.removeItem('mason-sample-bag');localStorage.removeItem('mason-gift-note')});await page.reload();await page.locator('#collectionsearch').fill('Contour');assert.equal(await page.locator('.product').count(),1);await page.locator('#collectionsearch').fill('');await page.locator('#collectionsort').selectOption('price-high');assert.equal(await page.locator('.product').first().getAttribute('data-product'),'MM04');await page.locator('#collectionsort').selectOption('featured');await page.locator('[data-save=MM01]').click();await page.locator('[data-filter=saved]').click();assert.equal(await page.locator('.product').count(),1);await page.reload();await page.locator('[data-filter=saved]').click();assert.equal(await page.locator('.product').count(),1);await page.locator('[data-filter=all]').click();
 for(const id of ['MM01','MM02','MM03'])await page.locator(`[data-compare=${id}]`).click();await page.locator('[data-compare=MM04]').click();await page.getByText('Compare up to three objects. Remove one to add another.',{exact:true}).waitFor();assert.equal(await page.locator('[data-compare][aria-pressed=true]').count(),3);await page.locator('#opencompare').click();assert.equal(await page.locator('.comparison thead th').count(),4);await snap('mason-comparison');await page.locator('[data-compare-open=MM01]').click();await page.locator('#detailsizeguide').click();assert.ok(await page.locator('#sizeguidebody').textContent().then(s=>s.includes('16.5 mm')));await page.locator('[data-close=sizeguidedialog]').click();await page.locator('#size').selectOption('US 7');await page.locator('#addtobag').click();await page.locator('#bag').click();await page.locator('#giftnote').fill('A graduation gift.');const selectionDL=page.waitForEvent('download');await page.locator('#savebag').click();const selection=await selectionDL;assert.ok((await fs.readFile(await selection.path(),'utf8')).includes('A graduation gift.'));await page.locator('[data-remove]').click();assert.equal(await page.locator('.bagrow').count(),0);await page.locator('[data-close=bagdialog]').click();await page.locator('#clearcompare').click();await snap('mason-desktop');checks.push('珠宝：搜索排序、收藏刷新保留、三件对比上限、对比至详情、尺码参考、赠礼备注导出与移除购物袋');
 for(const route of ['salon/index.html','expo/index.html','mason/index.html']){await page.setViewportSize({width:390,height:844});await page.goto(base+route);assert.ok(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth));if(route.startsWith('expo')){for(const view of ['registration','tickets','agenda','attendees','checkin','booths','reports','messages']){await go(view);assert.ok(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth),'Mobile overflow '+view)}await page.locator('#preview').click();assert.ok(await page.locator('#publicdialog').evaluate(d=>d.scrollWidth<=d.clientWidth));await snap('expo-public-mobile')}if(route.startsWith('mason')){await page.locator('[data-compare=MM01]').click();await page.locator('[data-compare=MM02]').click();await page.locator('#opencompare').click();assert.ok(await page.locator('#comparedialog').evaluate(d=>d.scrollWidth<=d.clientWidth));await snap('mason-comparison-mobile')}}
 assert.deepEqual(errors,[]);checks.push('新版所有会展页面与关键弹窗：390px 手机检查，无页面溢出或 JS 运行错误');
 await fs.writeFile(new URL('v2-checks.json',out),JSON.stringify({passed:true,checks,errors},null,2));console.log(JSON.stringify({passed:true,checks,errors}));
}catch(error){console.error(JSON.stringify({error:String(error),errors,url:page.url()}));await page.screenshot({path:fileURLToPath(new URL('outputs/v2/failure.png',root)),fullPage:true});throw error}finally{await browser.close()}
