import {chromium} from 'playwright';
import fs from 'node:fs/promises';
import {fileURLToPath} from 'node:url';
import assert from 'node:assert/strict';
const root=new URL('./',import.meta.url),out=new URL('outputs/review/',root);await fs.mkdir(out,{recursive:true});await fs.mkdir(new URL('outputs/v2/',root),{recursive:true});const browser=await chromium.launch({channel:'chrome',headless:true});const context=await browser.newContext({viewport:{width:1440,height:1000},acceptDownloads:true});const page=await context.newPage();const errors=[];page.on('pageerror',e=>errors.push(e.message));const checks=[];const base='http://127.0.0.1:8765/';
async function screenshot(name){await page.screenshot({path:fileURLToPath(new URL(name+'.png',out)),fullPage:true})}
await page.goto(base+'salon/index.html');await page.getByRole('heading',{name:'经营总览',exact:true}).waitFor();assert.equal(await page.locator('.kpi .value').first().textContent(),'¥29,660.00');await page.locator('#store').selectOption({label:'大学城店'});assert.ok((await page.locator('.kpi .value').first().textContent())!=='¥29,660.00');await page.locator('#store').selectOption('');await page.getByRole('button',{name:'到账核查',exact:true}).click();await page.locator('#onlyissues').check();assert.equal(await page.locator('tbody tr').count(),8);checks.push('salon: filters, 4 pending + 4 differences');await page.getByRole('button',{name:'经营总览',exact:true}).click();await screenshot('salon-desktop');
await page.getByRole('button',{name:'导出当前流水'}).click();const parsed=await page.evaluate(()=>Salon.parseCSV('id,date\n"X,1","2026-09-01"'));assert.deepEqual(parsed,[['id','date'],['X,1','2026-09-01']]);await page.locator('#file').setInputFiles(fileURLToPath(new URL('docs/salon/示例流水.csv',root)));await page.getByText('已导入 150 笔流水',{exact:true}).waitFor();await page.locator('#file').setInputFiles({name:'bad.csv',mimeType:'text/csv',buffer:Buffer.from('id,date,store,tech,service,customer,paid,refund,fee,bank,channel\nD1,2026-09-01,A,B,S,C,,0,0,,微信')});await page.getByText(/paid 金额错误/).waitFor();assert.equal(await page.evaluate(()=>Salon.getData().length),150);checks.push('salon: valid import, quoted CSV, rejects missing numeric input atomically');
await page.goto(base+'expo/index.html');await page.getByRole('button',{name:'重置样品'}).click();await screenshot('expo-desktop');await page.getByRole('button',{name:'现场签到',exact:true}).click();await page.locator('#checksearch').fill('G005');await page.getByRole('button',{name:'查找',exact:true}).click();await page.getByRole('button',{name:'确认签到',exact:true}).click();assert.equal(await page.evaluate(()=>Expo.getState().guests.filter(g=>g.checked).length),5);assert.ok(await page.getByRole('button',{name:'已完成',exact:true}).isDisabled());checks.push('expo: check-in, duplicate prevention');
await page.getByRole('button',{name:'新建活动'}).click();await page.locator('#eventform [name=name]').fill('验收测试活动');await page.locator('#eventform [name=location]').fill('测试场馆');await page.locator('#eventform [name=capacity]').fill('1');await page.getByRole('button',{name:'创建草稿'}).click();await page.locator('.card').filter({hasText:'验收测试活动'}).getByRole('button',{name:'发布活动'}).click();await page.locator('.card').filter({hasText:'验收测试活动'}).getByRole('button',{name:'管理活动'}).click();await page.locator('#fieldcompany').uncheck();await page.getByRole('button',{name:'保存配置'}).click();await page.getByRole('button',{name:'测试填写报名'}).click();assert.equal(await page.locator('#guestform [name=company]').count(),0);await page.locator('#guestform [name=name]').fill('演示审批者');await page.locator('#guestform [name=phone]').fill('13912345678');await page.getByRole('button',{name:'提交报名'}).click();await page.getByRole('button',{name:'测试填写报名'}).click();await page.getByText('报名人数已达上限',{exact:true}).waitFor();checks.push('expo: create/publish, optional fields, register, capacity guard');await page.getByRole('button',{name:'展位管理',exact:true}).click();await page.locator('[data-booth=A01]').click();await page.locator('#boothform [name=company]').fill('测试参展社');await page.locator('#boothform [name=contact]').fill('张同学');await page.locator('#boothform [name=phone]').fill('13812345678');await page.getByRole('button',{name:'保存分配'}).click();assert.ok(await page.locator('[data-booth=A01]').textContent().then(x=>x.includes('测试参展社')));await page.reload();assert.ok(await page.evaluate(()=>Expo.getState().events.some(x=>x.name==='验收测试活动')));checks.push('expo: booth allocation, survives reload');await page.getByRole('button',{name:'重置样品'}).click();
await page.goto(base+'mason/index.html');await page.evaluate(()=>{localStorage.removeItem('mason-sample-bag')});await page.reload();await screenshot('mason-desktop');await page.getByRole('button',{name:'Cuffs',exact:true}).click();assert.equal(await page.locator('.product').count(),1);await page.locator('.product').click();await page.locator('#size').selectOption('Medium');await page.getByRole('button',{name:'Add to bag',exact:true}).click();await page.locator('#bag').click();await page.locator('[data-plus]').click();assert.ok((await page.locator('.bagtotal strong').textContent())==='$456.00');await page.locator('[data-minus]').click();const dl=page.waitForEvent('download');await page.getByRole('button',{name:'Download selection'}).click();const downloaded=await dl;assert.equal(downloaded.suggestedFilename(),'mason-metal-selection.txt');await page.getByRole('button',{name:'Close bag'}).click();await page.getByRole('button',{name:'All objects',exact:true}).click();checks.push('mason: filter, detail, sizes, bag quantity, selection download');
await page.getByRole('button',{name:'Contact the studio'}).click();await page.locator('#contactform [name=name]').fill('Review');await page.locator('#contactform [name=email]').fill('sample@example.com');await page.locator('#contactform [name=message]').fill('Design approval sample');const msg=page.waitForEvent('download');await page.getByRole('button',{name:'Download your message'}).click();assert.equal((await msg).suggestedFilename(),'studio-message.txt');checks.push('mason: message downloaded without sending');
for(const [route,name]of [['salon/index.html','salon-mobile'],['expo/index.html','expo-mobile'],['mason/index.html','mason-mobile'],['index.html','review-mobile']]){await page.setViewportSize({width:390,height:844});await page.goto(base+route);assert.ok(await page.evaluate(()=>document.documentElement.scrollWidth<=window.innerWidth),name+' horizontal overflow');await screenshot(name)}await page.setViewportSize({width:1440,height:1000});await page.goto(base);await screenshot('review-desktop');assert.deepEqual(errors,[]);checks.push('all: desktop/mobile render, no JS runtime errors, no page horizontal overflow');await fs.writeFile(new URL('browser-checks.json',out),JSON.stringify({passed:true,checks,errors},null,2));console.log(JSON.stringify({passed:true,checks,errors}));await browser.close();
