import {chromium} from 'playwright';
import assert from 'node:assert/strict';
import fs from 'node:fs/promises';
import path from 'node:path';
import {fileURLToPath} from 'node:url';
const root=fileURLToPath(new URL('../',import.meta.url));const out=path.join(root,'screenshots');await fs.mkdir(out,{recursive:true});await fs.mkdir(path.join(root,'validation'),{recursive:true});
const base=process.env.BASE_URL||'http://127.0.0.1:8770/';
const browser=await chromium.launch({channel:'chrome',headless:true});
const ctx=await browser.newContext({viewport:{width:1440,height:1000},acceptDownloads:true});
const page=await ctx.newPage();const errors=[],checks=[];page.on('pageerror',e=>errors.push(e.message));
const nav=async(name)=>{await page.locator('nav').getByRole('button',{name,exact:true}).click();};
const act=async(name)=>{await page.getByRole('button',{name,exact:true}).click();};
const fill=async(name,value)=>{await page.locator('dialog').getByLabel(name,{exact:true}).fill(String(value));};
const choose=async(name,value)=>{await page.locator('dialog').getByLabel(name,{exact:true}).selectOption(value);};
const submit=async()=>{await page.locator('dialog button[type=submit]').click();};
const state=async(type)=>page.evaluate(type=>JSON.parse(localStorage.getItem('eleduck:'+type+':v1')),type);
async function open(type){await page.goto(base+type+'/index.html');await page.evaluate(type=>localStorage.removeItem('eleduck:'+type+':v1'),type);await page.reload();try{await page.locator('h1').waitFor({timeout:5000});}catch(err){console.error(JSON.stringify({type,errors,body:await page.locator('body').textContent()}));throw err;}}
await open('ops');await nav('审批队列');await page.locator('[data-id="AP-1001"]').click();await fill('审批意见','测试：预算已核对');await submit();assert.equal((await state('ops')).requests[0].status,'财务审核');await page.locator('[data-id="AP-1001"]').click();await fill('审批意见','测试：凭据已核对');await submit();assert.equal((await state('ops')).requests[0].status,'已批准');await nav('合同回款');await page.locator('[data-id="CT-001"]').click();await fill('本次金额（元）','999999');await submit();assert.equal((await state('ops')).contracts[0].received,2400000);assert.equal(await page.locator('dialog').isVisible(),true);await fill('本次金额（元）','1000');await submit();assert.equal((await state('ops')).contracts[0].received,2500000);checks.push('ops: two-stage approvals, overpayment rejected atomically, partial collection');
await open('orders');await nav('异常跟进');assert.equal(await page.locator('tbody tr').count(),2);await page.locator('[data-action=orders-move][data-id="JP-260901"]').click();await submit();assert.equal((await state('orders')).orders[0].status,'采购中');await page.locator('[data-action=orders-follow][data-id="JP-260901"]').click();await fill('负责人','验收负责人');await fill('跟进备注','已核对采购进度');await submit();await page.reload();assert.equal((await state('orders')).orders[0].owner,'验收负责人');checks.push('orders: exception queue, procurement flow, follow-up persistence');
await open('fish');await page.locator('[data-action=fish-favorite][data-id=SP-1]').click();await nav('我的收藏');assert.equal(await page.locator('.spot').count(),2);await page.locator('[data-action=fish-catch-for][data-id=SP-1]').click();await fill('鱼种','鲤鱼');await fill('饵料','玉米');await fill('重量（kg）','.8');await submit();await nav('渔获日志');assert.equal(await page.locator('tbody').first().locator('tr').count(),2);checks.push('fish: favorite filtering, validated catch journal');
await open('fresh');await page.locator('[data-action=fresh-add][data-id=P-1]').click();await page.locator('[data-action=fresh-add][data-id=P-1]').click();await nav('购物车');await act('填写地址并演示下单');await fill('收货人（虚构）','示例收货人');await fill('收货地址（虚构）','虚构小区 1 号');await submit();let fresh=await state('fresh');assert.equal(fresh.products[0].stock,26);assert.equal(fresh.orders[0].total,1780);await nav('订单履约');await act('取消订单');await fill('输入“取消”确认','取消');await submit();fresh=await state('fresh');assert.equal(fresh.products[0].stock,28);assert.equal(fresh.orders[0].status,'已取消');await nav('供应采购');await act('立即截单');await fill('输入“截单”确认；该批次将停止接收订单','截单');await submit();await nav('选购商品');assert.equal(await page.locator('[data-action=fresh-add]:not([disabled])').count(),0);checks.push('fresh: checkout totals, stock reduction, cancellation recovery, cutoff enforcement');
await open('bom');assert.ok(await page.getByText('¥370.60',{exact:true}).count());await act('新增结构关系');await choose('父物料','SCREW-1');await choose('子物料','DEV-01');await submit();assert.equal(await page.locator('dialog').isVisible(),true);assert.ok((await page.locator('#toast').textContent()).includes('循环'));await page.locator('dialog [data-close]').first().click();await page.locator('#bom-qty').fill('20');await act('更新计算');assert.equal((await state('bom')).quantity,20);await nav('迁移核查');const waiting=page.waitForEvent('filechooser');await act('导入并预检');const chooser=await waiting;await chooser.setFiles({name:'cycle.json',mimeType:'application/json',buffer:Buffer.from(JSON.stringify({parts:[{id:'A',name:'A',unit:'个',cents:1,stock:0},{id:'B',name:'B',unit:'个',cents:1,stock:0}],edges:[{parent:'A',child:'B',qty:1},{parent:'B',child:'A',qty:1}]}))});await page.getByText(/预检 失败/).waitFor();assert.equal((await state('bom')).parts.length,6);checks.push('bom: costs, cyclic relation rejected, demand recalculation, invalid migration leaves data intact');
await open('qa');await act('新建执行批次');await submit();await nav('执行批次');await page.locator('[data-action=qa-result]').first().click();await choose('执行结果','失败');await fill('实际执行证据与环境','个人演示：Chrome 刷新后状态回退');await fill('缺陷标题（失败时必填）','阶段保存失败');await fill('实际错误结果（失败时必填）','已联系阶段返回新建');await submit();let qa=await state('qa');assert.equal(qa.defects.length,1);assert.equal(qa.runs[0].results.length,1);await nav('缺陷跟进');await act('处理');await choose('下一状态','已关闭');await fill('处理或回归证据','尝试未回归关闭');await submit();assert.equal((await state('qa')).defects[0].status,'待处理');await page.locator('dialog [data-close]').first().click();await nav('执行批次');await act('记录回归');await fill('实际执行证据与环境','个人演示回归：保存后刷新三次一致');await submit();await nav('缺陷跟进');await act('处理');await choose('下一状态','已关闭');await fill('处理或回归证据','关联用例回归通过');await submit();assert.equal((await state('qa')).defects[0].status,'已关闭');checks.push('qa: failed evidence creates linked defect; no close before passed regression; result history retained');
// Screenshots use fresh demo state, never test data or private user data.
for(const type of ['ops','orders','fish','fresh','bom','qa']){
 await open(type);await page.screenshot({path:path.join(out,type+'-desktop.png'),fullPage:true});
 await page.setViewportSize({width:390,height:844});await page.screenshot({path:path.join(out,type+'-mobile.png'),fullPage:true});assert.ok(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth),type+' horizontal overflow');
 for(const name of await page.locator('nav button').allTextContents()){await page.locator('nav button').filter({hasText:name.trim()}).click();assert.ok(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth),type+' tab overflow');}
 await page.setViewportSize({width:1440,height:1000});
}
await open('orders');const dl=page.waitForEvent('download');await act('导出当前队列');assert.equal((await dl).suggestedFilename(),'渡单订单队列.csv');const backup=page.waitForEvent('download');await act('导出备份');const file=await backup;assert.equal(file.suggestedFilename(),'orders-备份.json');const buffer=await fs.readFile(await file.path());const fc=page.waitForEvent('filechooser');await act('恢复备份');await (await fc).setFiles({name:'restore.json',mimeType:'application/json',buffer});await fill('输入“恢复”确认替换本地数据','恢复');await submit();assert.equal((await state('orders')).orders.length,5);checks.push('shared: CSV download, backup roundtrip, six desktop + mobile screenshots, all mobile tabs without page overflow');
assert.deepEqual(errors,[]);await fs.writeFile(path.join(root,'validation','batch-browser.json'),JSON.stringify({passed:true,date:new Date().toISOString(),checks,errors},null,2));console.log(JSON.stringify({passed:true,checks,errors},null,2));await browser.close();
