import test from 'node:test';
import assert from 'node:assert/strict';
import * as M from '../docs/workbench/model.js';
test('All six seed states satisfy the backup contract',()=>{for(const type of Object.keys(M.meta))M.validateState(M.seed(type),type);});
test('Large expense requires financial review; terminal review is locked',()=>{const s=M.seed('ops');M.approve(s,'AP-1001','approve','预算已核对');assert.equal(s.requests[0].status,'财务审核');M.approve(s,'AP-1001','approve','凭据一致');assert.equal(s.requests[0].status,'已批准');assert.throws(()=>M.approve(s,'AP-1001','reject','重复'),/不能再审批/);M.approve(s,'AP-1002','approve','核对');assert.equal(s.requests[1].status,'已批准');});
test('Collections reject overpayment and do not mutate balance',()=>{const s=M.seed('ops');const c=s.contracts[0];assert.throws(()=>M.collect(s,c.id,2400001));assert.equal(c.received,2400000);M.collect(s,c.id,100000);assert.equal(c.received,2500000);});
test('Order flow prevents skipped procurement and requires tracking before shipment',()=>{const s=M.seed('orders');assert.throws(()=>M.changeOrder(s,'JP-260901','已发货','',''),/不允许/);M.changeOrder(s,'JP-260901','采购中','','');assert.throws(()=>M.changeOrder(s,'JP-260901','待发货','',''),/全部到货/);M.receiveOrder(s,'JP-260901',1,'核对首批');assert.equal(s.orders[0].received,1);M.receiveOrder(s,'JP-260901',2,'核对剩余');M.changeOrder(s,'JP-260901','待发货','','');assert.throws(()=>M.changeOrder(s,'JP-260901','已发货','',''),/物流单号/);M.changeOrder(s,'JP-260901','已发货','DEMO-T-123','');assert.equal(s.orders[0].status,'已发货');assert.equal(M.orderException(s.orders[0],'2026-10-02'),true);});
test('Fresh checkout validates all inventory atomically; cancellation restores stock once',()=>{const s=M.seed('fresh');M.cartAdd(s,'P-1',2);M.cartAdd(s,'P-2',3);const before=M.copy(s);s.products[1].stock=2;assert.throws(()=>M.checkout(s,'示例收货人','虚构地址'),/库存不足/);assert.equal(s.products[0].stock,before.products[0].stock);assert.equal(s.orders.length,0);s.products[1].stock=35;const o=M.checkout(s,'示例收货人','虚构地址');assert.equal(o.total,2*890+3*1690);assert.equal(s.products[0].stock,26);M.freshMove(s,o.id,'已取消');assert.equal(s.products[0].stock,28);assert.throws(()=>M.freshMove(s,o.id,'已取消'));assert.equal(s.products[0].stock,28);M.validateState(s,'fresh');});
test('Fresh cutoff stops additions and checkout; order price is a snapshot',()=>{const s=M.seed('fresh');M.cartAdd(s,'P-3',1);const o=M.checkout(s,'示例','地址');s.products[2].cents=3000;assert.equal(o.items[0].cents,1890);s.batch.closed=true;assert.throws(()=>M.cartAdd(s,'P-1'),/截单/);assert.throws(()=>M.checkout(s,'示例','地址'),/截单/);});
test('BOM rolls up shared leaf demand before inventory and costs all levels',()=>{const s=M.seed('bom');assert.equal(M.bomCost(s),37060);const leaves=M.explode(s);const screws=leaves.find(p=>p.id==='SCREW-1');assert.equal(screws.need,120);assert.equal(screws.shortage,0);assert.equal(leaves.find(p=>p.id==='BOARD-1').shortage,4);s.parts.find(p=>p.id==='SENS-1').cents=5000;assert.equal(M.bomCost(s),38660);});
test('Migration rejects duplicate keys, missing references and cycles before replacing data',()=>{const s=M.seed('bom');const original=M.copy(s);const cyclic=M.copy(s.edges);cyclic.push({parent:'SCREW-1',child:'DEV-01',qty:1});assert.throws(()=>M.validateBom(s.parts,cyclic),/循环/);assert.equal(M.migrationCheck({parts:s.parts,edges:[{parent:'DEV-01',child:'unknown',qty:1}]}).ok,false);assert.equal(M.migrationCheck({parts:[...s.parts,s.parts[0]],edges:s.edges}).ok,false);assert.deepEqual(s,original);});
test('QA snapshots remain stable; failed results create traceable defects; history is preserved',()=>{const s=M.seed('qa');const r=M.startRun(s,'手工回归','示例 Chrome');const title=r.cases[0].title;s.cases[0].title='新标题';assert.equal(r.cases[0].title,title);assert.throws(()=>M.recordResult(s,r.id,'TC-001','失败','观察到错误',null),/附缺陷/);assert.equal(r.results.length,0);M.recordResult(s,r.id,'TC-001','失败','示例：阶段刷新后回退',{title:'阶段未保存',actual:'刷新后返回新建',severity:'P1'});assert.equal(s.defects[0].caseId,'TC-001');M.recordResult(s,r.id,'TC-001','通过','示例回归：刷新后三次结果一致');assert.equal(r.results.length,2);assert.equal(M.qaSummary(r).passed,1);assert.equal(M.qaSummary(r).failed,0);M.validateState(s,'qa');});
test('Malformed backup references and incorrect order totals are rejected',()=>{const fish=M.seed('fish');fish.favorites=['NO-SUCH-SPOT'];assert.throws(()=>M.validateState(fish,'fish'),/收藏引用/);const fresh=M.seed('fresh');M.cartAdd(fresh,'P-1',1);M.checkout(fresh,'示例','地址');fresh.orders[0].total++;assert.throws(()=>M.validateState(fresh,'fresh'),/金额不一致/);assert.throws(()=>M.validateState(M.seed('orders'),'ops'),/类型/);});

test('Procurement belongs to the current batch while historical orders remain',()=>{const s=M.seed('fresh');M.cartAdd(s,'P-1',2);M.checkout(s,'示例','地址');assert.equal(M.procurement(s)[0].qty,2);s.batch.id='GB-NEXT';assert.equal(M.procurement(s).length,0);assert.equal(s.orders.length,1);});
