import {chromium} from 'playwright';
import assert from 'node:assert/strict';
import fs from 'node:fs/promises';
import {fileURLToPath} from 'node:url';
const base=process.env.PORTFOLIO_URL||'http://127.0.0.1:8770/';
const browser=await chromium.launch({channel:'chrome',headless:true});const ctx=await browser.newContext({viewport:{width:1440,height:1000}});const page=await ctx.newPage();const errors=[];page.on('pageerror',err=>errors.push(err.message));
await page.goto(base);assert.equal(await page.locator('.card').count(),9);await page.getByRole('button',{name:'数据与业务',exact:true}).click();assert.equal(await page.locator('.card:visible').count(),4);await page.getByRole('button',{name:'移动与交互',exact:true}).click();assert.equal(await page.locator('.card:visible').count(),3);await page.getByRole('button',{name:'全部作品',exact:true}).click();assert.equal(await page.locator('.card:visible').count(),9);
await page.locator('.preview img').evaluateAll(images=>images.forEach(img=>img.loading='eager'));await page.waitForFunction(()=>[...document.querySelectorAll('.preview img')].every(img=>img.complete&&img.naturalWidth>0));await page.locator('.preview img').evaluateAll(images=>Promise.all(images.map(img=>img.decode())));for(const preview of await page.locator('.preview').all())await preview.scrollIntoViewIfNeeded();await page.evaluate(()=>scrollTo(0,0));await page.evaluate(()=>new Promise(resolve=>requestAnimationFrame(()=>requestAnimationFrame(resolve))));await fs.mkdir(fileURLToPath(new URL('../outputs/review/',import.meta.url)),{recursive:true});await page.screenshot({path:fileURLToPath(new URL('../outputs/review/portfolio-desktop.png',import.meta.url)),fullPage:true});await page.setViewportSize({width:390,height:844});await page.screenshot({path:fileURLToPath(new URL('../outputs/review/portfolio-mobile.png',import.meta.url)),fullPage:true});assert.ok(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth));
await page.goto(base+'research/');assert.ok(await page.getByRole('heading',{name:'六条需求与竞品对照',exact:true}).count());assert.ok(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth));
const checks=[];for(const slug of ['salon','expo','mason','ops','orders','fish','fresh','bom','qa']){const response=await page.goto(base+slug+'/');assert.equal(response.status(),200,slug);await page.locator('h1').first().waitFor();checks.push({project:slug,status:response.status()});}
for(const file of ['电鸭作品集发布材料.docx','电鸭九项目成品.zip','门店经营模板.xlsx','mason-metal-child.zip']){const response=await page.request.head(base+'downloads/'+encodeURIComponent(file));assert.equal(response.status(),200,file);checks.push({download:file,status:200,bytes:response.headers()['content-length']});}
assert.deepEqual(errors,[]);const result={passed:true,base,date:new Date().toISOString(),portfolio_cards:9,category_filter:'pass',mobile_overflow:false,checks,errors};await fs.writeFile(fileURLToPath(new URL('../validation/portfolio-links.json',import.meta.url)),JSON.stringify(result,null,2));console.log(JSON.stringify(result,null,2));await browser.close();
